from src.config import ReaderConfig, PlotterConfig
from src.data_plotting import BubblePlotter

sorted_frequencies = [('franchise', 1313), ('franchisee', 818), ('franchisor', 794), ('innovation', 397), ('strategy', 113), ('brand', 111), ('franchise system', 106), ('territory', 48), ('human capital', 39), ('franchise fee', 32), ('business strategy', 26), ('entrepreneur', 22), ('initial investment', 20), ('franchise agreement', 18), ('business plan', 14), ('moral hazard', 13), ('economic growth', 13), ('leverage', 12), ('monopoly', 12), ('franchise network', 11), ('franchise operations', 11), ('trademark', 11), ('franchise management', 10), ('options', 10), ('leadership', 9), ('cash flow', 9), ('site selection', 8), ('corporation', 8), ('interest rates', 7), ('capital structure', 6), ('market penetration', 6), ('partnership', 6), ('target market', 6), ('bonds', 6), ('royalty fee', 6), ('diversification', 6), ('benchmarking', 5), ('signaling', 5), ('market research', 5), ('economic efficiency', 5), ('market economy', 5), ('private sector', 5), ('screening', 4), ('corporate finance', 4), ('franchise development', 4), ('securities', 4), ('financial statements', 4), ('franchise expansion', 4), ('balance sheet', 4), ('monetary policy', 4), ('e - commerce', 4), ('disposable income', 4), ('insurance', 4), ('strategic alliances', 4), ('monetary union', 4), ('opportunity cost', 3), ('product development', 3), ('corporate governance', 3), ('gross domestic product', 3), ('financial risk', 3), ('franchise disclosure', 3), ('franchise sales', 3), ('quotas', 3), ('globalization', 3), ('intellectual property', 3), ('franchisee recruitment', 3), ('business development', 3), ('marketing strategy', 2), ('market expansion', 2), ('subsidies', 2), ('productive efficiency', 2), ('capital markets', 2), ('risk management', 2), ('brand equity', 2), ('joint ventures', 2), ('core values', 2), ('purchasing power', 2), ('market intelligence', 2), ('swot analysis', 2), ('franchise investment', 2), ('business model', 2), ('startup', 2), ('supply chain', 2), ('business ethics', 2), ('organizational change', 2), ('franchise ownership', 2), ('international trade', 2), ('foreign direct investment', 2), ('financial stability', 2), ('arbitrage', 1), ('public goods', 1), ('financial markets', 1), ('budgeting', 1), ('strategic planning', 1), ('stakeholder', 1), ('commercial banks', 1), ('brand awareness', 1), ('profit margin', 1), ('discount rate', 1), ('profit maximization', 1)]

sorted_frequencies = sorted_frequencies[0:30]

plotter_config = PlotterConfig()
bp = BubblePlotter(plotter_config, len(sorted_frequencies))
bp.init_figure()
bp.set_name("2005 Papers: Most Used Words")
bp.add(sorted_frequencies)
bp.plot()
