import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget
from main_window import Ui_window  # Import the Ui_window class generated by pyuic


class MainWindow(QWidget, Ui_window):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("Basic PyQt Frame")

        self.close_1.clicked.connect(self.close)

    def close(self):
        sys.exit()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()  # Create the window instance
    window.show()  # Display the window
    sys.exit(app.exec_())  # Start the event loop
